services:
    database:
        image: 'mysql:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=userinfo
        container_name: mysqldb
        healthcheck:
            test: ["CMD", "mysqladmin","ping","-h","localhost"]
            timeout: 20s
            retries: 10
        networks:
            - my-network

    mypythonapp:
        build: ./
        container_name: mypythonapp
        depends_on:
            database:
                condition: service_healthy
        stdin_open: true
        tty: true
        networks:
            - my-network

networks:
 my-network:
